name: DAST

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP of Application'
        required: true
        default: '127.0.0.1'

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for uploading artifacts
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan on Application
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: "http://${{ github.event.inputs.server_ip }}"
          cmd_options: '-m 2'  # minimal spider
          fail_action: 'false' #do not fail on finding severity
          allow_issue_writing: 'false' #do not open issues in github
          artifact_name: dastreport  
          # rules_file_name: 'rules.tsv'       # optional

      - name: Print Alert Summary
        run: |
          high=$(jq '[.site[].alerts[] | select(.riskcode=="3")] | length' report_json.json)
          medium=$(jq '[.site[].alerts[] | select(.riskcode=="2")] | length' report_json.json)
          low=$(jq '[.site[].alerts[] | select(.riskcode=="1")] | length' report_json.json)
          info=$(jq '[.site[].alerts[] | select(.riskcode=="0")] | length' report_json.json)
          echo "High: $high"
          echo "Medium: $medium"
          echo "Low: $low"
          echo "Informational: $info"

      - name: Fail Pipeline if High Risk
        run: |
          high=$(jq '[.site[].alerts[] | select(.riskcode=="3")] | length' report_json.json)
          if [ "$high" -gt 0 ]; then
            echo "❌ High severity alerts found — blocking pipeline"
            exit 1
          fi
          echo "✅ No high severity issues"

# Reference for file names
      # - name: Upload ZAP Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: zap-report-artifact
      #     path: |
      #       report_html.html
      #       report_json.json
      #       report_md.md