name: DAST

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP of Application'
        required: true
        default: '127.0.0.1'

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline Scan on Juice Shop
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "http://${{ github.event.inputs.server_ip }}"
          cmd_options: '-m 2 --fail-on=high'  # minimal spider, fail only on high severity
          # rules_file_name: 'rules.tsv'       # optional
