name: DAST

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP of Application'
        required: true
        default: '127.0.0.1'

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline Scan on Application
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "http://${{ github.event.inputs.server_ip }}"
          cmd_options: '-m 2'  # minimal spider
          fail_action: 'false' #do not fail on finding severity
          allow_issue_writing: 'false' #do not open issues in github
          artifact_name: 'zap-dast-report'      
          # rules_file_name: 'rules.tsv'       # optional

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-artifact
          path: |
            zap-report.html
            zap-report.json
            zap-report.md